gateway:
  namespace: istio-gateway
  name: public-http-8080
  selector:
    istio: istio-ingressgateway
  port:
    number: 8080
    name: http-8080
    protocol: HTTP
  hosts:
    - agyn.dev
    - api.agyn.dev
    - argocd.agyn.dev
    - litellm.agyn.dev
    - vault.agyn.dev

virtualServices:
  - name: agyn-dev-platform-ui
    namespace: istio-gateway
    hosts:
      - agyn.dev
    destination:
      host: platform-ui.platform.svc.cluster.local
      port: 3000
    timeout: 60s
  - name: api-agyn-dev-platform-server
    namespace: istio-gateway
    hosts:
      - api.agyn.dev
    destination:
      host: platform-server.platform.svc.cluster.local
      port: 3010
    timeout: 60s
  - name: argocd-agyn-dev
    namespace: istio-gateway
    hosts:
      - argocd.agyn.dev
    destination:
      host: argo-cd-argocd-server.argocd.svc.cluster.local
      port: 8080
    timeout: 60s
    headers:
      request:
        set:
          X-Forwarded-Proto: http
          X-Forwarded-Port: "8080"
  - name: litellm-agyn-dev
    namespace: istio-gateway
    hosts:
      - litellm.agyn.dev
    destination:
      host: litellm.platform.svc.cluster.local
      port: 4000
    timeout: 60s
  - name: vault-agyn-dev
    namespace: istio-gateway
    hosts:
      - vault.agyn.dev
    destination:
      host: vault.platform.svc.cluster.local
      port: 8200
    timeout: 60s
